services:

  # ---------------------------------------------
  # API Gateway (Entry Point for Clients)
  # ---------------------------------------------

  api-gateway: # Name of the service
    build: ./services/api-gateway # Directory containing the Dockerfile for the API Gateway service
    ports:
      - "4000:8000" # Expose port 8000 of the container to port 4000 on the host
    environment: # Define environment variables for the API Gateway to know how to reach the operation services
      - MATH_ADD_SERVICE_URL=http://math-add:8000
      - MATH_SUBTRACT_SERVICE_URL=http://math-subtract:8000
      - MATH_MULTIPLY_SERVICE_URL=http://math-multiply:8000
      - MATH_DIVIDE_SERVICE_URL=http://math-divide:8000
    depends_on: # Define services to depend on to ensure they start first
      - math-add
      - math-subtract
      - math-multiply
      - math-divide

  # ---------------------------------------------
  # Core Business Logic (Operation Services)
  # ---------------------------------------------

  math-add: # Name of the service 
    build: ./services/math-add # Directory containing the Dockerfile for the math-add service
    ports:
      - "8011:8000"  # Expose port 8000 of the container to port 8011 on the host

  math-subtract: # Name of the service
    build: ./services/math-subtract # Directory containing the Dockerfile for the math-subtract service
    ports:
      - "8012:8000"  # Expose port 8000 of the container to port 8012 on the host

  math-multiply: # Name of the service
    build: ./services/math-multiply # Directory containing the Dockerfile for the math-multiply service
    ports:
      - "8013:8000"  # Expose port 8000 of the container to port 8013 on the host

  math-divide: # Name of the service
    build: ./services/math-divide # Directory containing the Dockerfile for the math-divide service
    ports:
      - "8014:8000"  # Expose port 8000 of the container to port 8014 on the host