import os


IDENTITY_SERVICE_URL = os.getenv("IDENTITY_SERVICE_URL", "http://localhost:8010")
MATH_ADD_SERVICE_URL = os.getenv("MATH_ADD_SERVICE_URL", "http://localhost:8011")
MATH_SUBTRACT_SERVICE_URL = os.getenv("MATH_SUBTRACT_SERVICE_URL", "http://localhost:8012")
MATH_MULTIPLY_SERVICE_URL = os.getenv("MATH_MULTIPLY_SERVICE_URL", "http://localhost:8013")
MATH_DIVIDE_SERVICE_URL = os.getenv("MATH_DIVIDE_SERVICE_URL", "http://localhost:8014")

RATE_LIMIT_REQUESTS = int(os.getenv("RATE_LIMIT_REQUESTS", "60"))
RATE_LIMIT_WINDOW_SECONDS = int(os.getenv("RATE_LIMIT_WINDOW_SECONDS", "60"))
UPSTREAM_TIMEOUT_SECONDS = float(os.getenv("UPSTREAM_TIMEOUT_SECONDS", "5"))

LEDGER_SERVICE_URL = os.getenv("LEDGER_SERVICE_URL", "http://localhost:8021")
LEDGER_PUBLISH_TIMEOUT_SECONDS = float(os.getenv("LEDGER_PUBLISH_TIMEOUT_SECONDS", "0.5"))
JWT_SECRET = os.getenv("JWT_SECRET", "")
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM", "HS256")
